cookie:
  expiry_days: 30
  key: taifa
  name: feeding

credentials:
  usernames:
    admin:
      email: suhas11533@gmail.com
      failed_login_attempts: 0
      logged_in: false
      name: Admin
      password: $2b$12$WzNVXOpECwM7/cyMLmHDXOpzUreYo3Aa9ZZSgoYPLfKsnZUkY3.NW

    suhas:
      email: suhas11533@gmail.com
      failed_login_attempts: 0
      logged_in: false
      name: Suhas
      password: $2b$12$WzNVXOpECwM7/cyMLmHDXOpzUreYo3Aa9ZZSgoYPLfKsnZUkY3.NW

pre-authorized:
  emails:
    - suhas11533@gmail.com
