cookie:
  expiry_days: 30
  key: taifa
  name: feeding
credentials:
  usernames:
    bkaitany:
      email: benjaminkipkem@gmail.com
      failed_login_attempts: 0
      logged_in: false
      name: Benjamin Kaitany
      password: $2b$12$pHxMgRW9iGXiM7DrrV7DNuiFEjF2B1kaKt4Q8v/HTq/ym3wEHDAbW
    jogendo:
      email: jogendo@gmail.com
      failed_login_attempts: 0
      logged_in: false
      name: Jonam Ogendo
      password: $2b$12$43mqvIzKnppoMBrL5AFOeulS1JQifMwA27HOxlkD23o9tVLa3GSNe
pre-authorized:
  emails:
  - benjaminkipkem@gmail.com
